Stat auto (Price, Supply, MC)
tesla-safe/tesla-safe-web pull request #47
Opened 2021-05-26 16:29 UTC by Shaharyar-saleem

2021-05-26 20:34 UTC, bobachef requested changes
some suggestions

2021-05-26 20:34 UTC, bobachef commented on js/stats.js
> +}
shouldn't use `let` but also easier to just name the function.
```
async function getPriceData() {
  let res  = await fetch("https://api.dex.guru/v1/tokens/0x3504de9e61fdff2fc70f5cc8a6d1ee493434c1aa-bsc")
  let data = await res.json();
  return data;
}
```

2021-05-26 20:34 UTC, bobachef commented on js/stats.js
> +  let data = await res.json();
res.json doesn't return a promise so no need to await it...

2021-05-26 20:34 UTC, bobachef commented on js/stats.js
> +let supply = async function () {
same thing change this to 

```async function getSupplyData()```

2021-05-26 20:34 UTC, bobachef commented on js/stats.js
> +  })
```
const priceData = await getPriceData()
let price =  parseFloat(data.priceUSD).toFixed(14);
```

2021-05-26 20:34 UTC, bobachef commented on js/stats.js
> +async function caller(){
rename this function to `calculatePriceSupplyAndDisplay`

2021-05-26 20:34 UTC, bobachef commented on js/stats.js
> +  let data = await res.json();
remove `await`

2021-05-26 20:34 UTC, bobachef commented on js/stats.js
> +  display(_coinPrice , _coinSupply);
```
const TOTAL_SUPPLY = 1000000000000000
const supplyData = await getSupplyData()
const burnedSupply = supplyData.result.slice(0,15);
const supply = TOTAL_SUPPLY-burnedSupply;

display(price, supply)

```

2021-05-26 20:34 UTC, bobachef commented on js/stats.js
> +      price = parseFloat(data.priceUSD).toFixed(14);
`let price = parseFloat(data.priceUSD).toFixed(14);`

2021-05-27 00:28 UTC, bobachef commented
Please resolve the conflicts also

2021-05-27 07:56 UTC, Shaharyar-saleem commented on js/stats.js
> +}
const getPriceData = async function () {
  let res  = await fetch("https://api.dex.guru/v1/tokens/0x3504de9e61fdff2fc70f5cc8a6d1ee493434c1aa-bsc")
  let data = res.json();
  return data;
}

2021-05-27 07:56 UTC, Shaharyar-saleem commented on js/stats.js
> +}
const getPriceData = async function () {
  let res  = await fetch("https://api.dex.guru/v1/tokens/0x3504de9e61fdff2fc70f5cc8a6d1ee493434c1aa-bsc")
  let data = res.json();
  return data;
}

2021-05-27 07:57 UTC, Shaharyar-saleem commented on js/stats.js
> +  let data = await res.json();
removed

2021-05-27 08:00 UTC, Shaharyar-saleem commented on js/stats.js
> +  display(_coinPrice , _coinSupply);
followed

2021-05-27 08:00 UTC, Shaharyar-saleem commented on js/stats.js
> +}
followed

2021-05-27 08:02 UTC, Shaharyar-saleem commented on js/stats.js
> +let supply = async function () {
followed

2021-05-27 08:03 UTC, Shaharyar-saleem commented on js/stats.js
> +async function caller(){
followed

2021-05-27 08:03 UTC, Shaharyar-saleem commented on js/stats.js
> +  let data = await res.json();
followed

2021-05-27 18:19 UTC, Shaharyar-saleem reviewed
reviewed index.html page

2021-05-27 19:00 UTC, bobachef approved these changes
looks good

2021-05-27 19:02 UTC, merged